export const UserTypes = {
    LOG_IN: "LOG_IN",
    REGISTER: "REGISTER"
}

export const CourseType = {
    GET_COURSE_LISTS : "GET_COURSE_LISTS",
    SET_ROUTER_DETAIL:"SET_ROUTER_DETAIL",
    GET_ROUTER_DETAIL: "GET_ROUTER_DETAIL",
    GET_COURSE_BY_ID: "GET_COURSE_BY_ID",
    GET_LESSON_BY_COURSE:"GET_LESSON_BY_COURSE",
}