export const UserTypes = {
    LOG_IN: "LOG_IN",
    REGISTER: "REGISTER",
    ADD_COURSE:"ADD_COURSE",
    UPDATE_COURSE_STUDYING:"UPDATE_COURSE_STUDYING",
    RE_RENDER:"RE_RENDER"
}

export const CourseType = {
    GET_COURSE_LISTS : "GET_COURSE_LISTS",
    SET_ROUTER_DETAIL:"SET_ROUTER_DETAIL",
    GET_ROUTER_DETAIL: "GET_ROUTER_DETAIL",
    GET_COURSE_BY_ID: "GET_COURSE_BY_ID",
    GET_LESSON_BY_COURSE:"GET_LESSON_BY_COURSE",
    SET_LOADING:"SET_LOADING"
}

